import localFont from "next/font/local";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
const iranYekan = localFont({
    src: [
        {
            path: "./fonts/iranyekanweblightfanum.ttf",
            weight: "100",
        },
        {
            path: "./fonts/iranyekanwebregularfanum.ttf",
            weight: "normal",
        },
        {
            path: "./fonts/iranyekanwebboldfanum.ttf",
            weight: "bold",
        },
        {
            path: "./fonts/iranyekanwebextraboldfanum.ttf",
            weight: "600",
        },
        {
            path: "./fonts/iranyekanwebblackfanum.ttf",
            weight: "800",
        },
    ],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" dir="rtl">
            <body className={`${iranYekan.className} antialiased`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
